app/routes/login.py
# app/routes/iniciarSesion.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session as flask_session
from app.models.operaciones import Operaciones

iniciarSesion_bp = Blueprint('login', __name__, template_folder="../../templates")

@iniciarSesion_bp.route("/", methods=["GET", "POST"])
def login():
    if flask_session.get("usuario_id") or flask_session.get("nombre"):
        return redirect(url_for("libros.ver_libros"))
    
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        usuario = Operaciones.buscarUsuario(email)
        if usuario and usuario.password == password:
            flask_session["usuario_id"] = usuario.id
            flask_session["nombre"] = usuario.nombre
            
            return redirect(url_for("libros.ver_libros"))
        else:
            flash("Credenciales incorrectas", "error")


    return render_template("login/login.html")

templates/login/login.html
{% extends "base.html" %} {% block title %} Iniciar Sesion {% endblock %} {%
block content %}
<h1>Iniciar Sesion</h1>
<div class="card">
  <form method="post" action="{{ url_for('login.login') }}">
    <table>
      <tr>
        <td><label for="email"> Email de Usuario </label></td>
        <td>
          <input
            type="text"
            name="email"
            id="email"
            placeholder="Introduzca su correo electronico"
          />
        </td>
      </tr>
      <tr>
        <td><label for="password">Contraseña de Usuario</label></td>
        <td>
          <input
            type="password"
            name="password"
            id="password"
            placeholder="Introduzca su contraseña"
          />
        </td>
      </tr>
      <tr>
        <td colspan="2"><input type="submit" value="Iniciar Sesion"></td>
      </tr>
    </table>
  </form>
</div>
{% endblock %}