app/routes/login.py
# app/routes/iniciarSesion.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session as flask_session
from app.models.operaciones import Operaciones

iniciarSesion_bp = Blueprint('login', __name__, template_folder="../../templates")

@iniciarSesion_bp.route("/", methods=["GET", "POST"])
def login():
    if flask_session.get("usuario_id") or flask_session.get("nombre"):
        return redirect(url_for("libros.ver_libros"))
    
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        usuario = Operaciones.buscarUsuario(email)
        if usuario and usuario.password == password:
            flask_session["usuario_id"] = usuario.id
            flask_session["nombre"] = usuario.nombre
            
            return redirect(url_for("libros.ver_libros"))
        else:
            flash("Credenciales incorrectas", "error")


    return render_template("login/login.html")

app/routes/logout.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session as flask_session

logout_bp = Blueprint('logout', __name__, template_folder="../../templates")

@logout_bp.route("/logout", methods=["GET", "POST"])
def logout():
    flask_session.clear()
    return redirect(url_for("login.login"))

templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>

    <header>
        <nav>
            <ul>
                {% if not session.get('nombre') %}
                <li><a href="{{ url_for('login.login') }}">Iniciar sesión</a></li>
                <li><a href="{{ url_for('signin.signin') }}">Crear cuenta</a></li>
                {% else %}

                <li><a href="{{ url_for('libros.ver_libros') }}">Ver Libro</a></li>

                {% if session.get('admin') %}
                <li><a href="{{ url_for('admin.adminpanel') }}">Panel Admin</a></li>
                <li><a href="{{ url_for('admin.mostrarCsv') }}">Importar csv</a></li>
                {% else %}
                <li><a href="{{ url_for('reservas.ver_reservas') }}">Ver Reservas</a></li>

                {% endif %}

                <li><a href="{{ url_for('logout.logout') }}">Cerrar sesión</a></li>
                {% endif %}
            </ul>


        </nav>
        <h1>COGE LO TUYO</h1>
    </header>

    <main>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="mensajes">
            {% for category, message in messages %}
            <div class="mensaje {{ category }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </main>

</body>

</html>

templates/verReservas.html
{% extends "base.html" %}
{% block title %} Ver reservas {% endblock %}

{% block content %}
<h1>Bienvenido {{ session['nombre'] }}</h1>
<h2>Libros reservados</h2>
{% if reservasUsu %}
<div class="grid-libros">
    {% for r in reservasUsu %}
    <div class="card-libro">
        <p class="titulo">{{ r.titulo }}</p>
        <img src="{{ url_for('static', filename='images/' + r.imagen) }}" alt="">
        <p class="descripcion">
            {{ r.descripcion}}
        </p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No hay reservas</p>
{% endif %}
{% endblock %}